#!/bin/bash
echo " input the first number"
read number1
echo " input the secondd number"
read number2 
echo " input the third number"
read number3

if [ $number1 -gt $number2 -a $number1 -gt $number3 ]
then 
echo "the input $number1 is greater"
else 
echo " $number1 is smaller "
fi
