#!/bin/bash  
#stores the system date in date variable
date=$(date)  
#stores the output of command in variable a i.e. in my case i am checking the status of service hylafax and from AWK i am getting the required string i want to compare
a=$(/etc/init.d/hylafax status | awk 'NR==2{print $9}') 
#storing string in another variable optional
c="$a"  
#input string to compare with
b="running..." 
#this if statement compares the string we got from service status with input strings and decides on base of that
if [ "$c" = "$b" ]  
#do nothing if strings are equal
then  
echo "faxq is running"  
#just for the logs
 echo "Faxq is running and date/time is $date" >> /root/hylafaxlogs.txt    
else
#just for logs
 echo "Faxq is NOT running and date/time is $date" >> /root/hylafaxlogs.txt 
#restart service if service was not running
/etc/init.d/hylafax restart  
#emailing that needful was doneusing the sendmail utility on linux
 echo -e "Faxq was stopped so i restarted it date/time is $date"  | mail -s "Hylafax Restarted" -c "xyz@xyz.com" ngn@nayatel.com,xyz@xyz.com
fi
